In [1]:
pip install -U transformers accelerate bitsandbytes peft trl datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.2)
Collecting transformers
  Downloading transformers-4.57.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.7 MB/s eta 0:00:00
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Collecting bitsandbytes
  Downloading bitsandbytes-0.48.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.0)
Collecting trl
  Downloading trl-0.25.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-4.4.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.9.0+cu126)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-22.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Downloading transformers-4.57.3-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 109.2 MB/s eta 0:00:00
Downloading bitsandbytes-0.48.2-py3-none-manylinux_2_24_x86_64.whl (59.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.4/59.4 MB 38.6 MB/s eta 0:00:00
Downloading trl-0.25.1-py3-none-any.whl (465 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.5/465.5 kB 39.4 MB/s eta 0:00:00
Downloading datasets-4.4.1-py3-none-any.whl (511 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.6/511.6 kB 37.1 MB/s eta 0:00:00
Downloading pyarrow-22.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (47.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 MB 57.4 MB/s eta 0:00:00
Installing collected packages: pyarrow, transformers, datasets, bitsandbytes, trl
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.2
    Uninstalling transformers-4.57.2:
      Successfully uninstalled transformers-4.57.2
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed bitsandbytes-0.48.2 datasets-4.4.1 pyarrow-22.0.0 transformers-4.57.3 trl-0.25.1

# Import Libraries

In [2]:
import os, json, torch
import pandas as pd
from datasets import Dataset
from collections import Counter
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    BitsAndBytesConfig, LogitsProcessor, LogitsProcessorList
)
from trl import SFTTrainer, SFTConfig
from peft import LoraConfig, PeftModel, TaskType

import os
os.environ["WANDB_DISABLED"] = "true"

# Mount Drive

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Configuration

In [22]:
Model = "mistralai/Mistral-7B-Instruct-v0.3"
BASE_DIR = "/content/drive/MyDrive/Colab Notebooks/DataSci_266_NLP/Final_Project"
OUTPUT_DIR = BASE_DIR + "/Drug_Review/mistral_cls_adapter_001"
os.makedirs(OUTPUT_DIR, exist_ok=True)

Train_path = BASE_DIR + "/Drug_Review/train.csv"
Val_path = BASE_DIR + "/Drug_Review/val.csv"
# Test_path = BASE_DIR + "/Drug_Review/test_medical_abstract.csv"

Labels = ["1-2 stars", "3-4 stars", "5-6 stars", "7-8 stars", "9-10 stars"]

In [23]:
train_df = pd.read_csv(Train_path, dtype={"text":str, "label":str})
display(train_df)

,drugName,condition,review,text,labels
0,zoloft,panic disorde,i have taken 25mg for anxiety for 8 years. i w...,zoloft | panic disorde | i have taken 25mg for...,4
1,exenatide,"diabetes, type 2",bydureon helped me get my a1c numbers down. if...,"exenatide | diabetes, type 2 | bydureon helped...",3
2,macrobid,bladder infection,i am on my seventh day on macrobid and still h...,macrobid | bladder infection | i am on my seve...,0
3,percocet,pain,i have severe back pain and leg pain associate...,percocet | pain | i have severe back pain and ...,4
4,ultram,ibromyalgia,this medicine was useful at first then your bo...,ultram | ibromyalgia | this medicine was usefu...,2
...,...,...,...,...,...
22157,sprintec,birth control,i started taking sprintec yesterday. within a ...,sprintec | birth control | i started taking sp...,0
22158,prednisone,gouty arthritis,ive tried most nsaids and non of them work for...,prednisone | gouty arthritis | ive tried most ...,4
22159,docosanol,herpes simplex,"i have had cold sore all my life, and usually ...",docosanol | herpes simplex | i have had cold s...,1
22160,amrix,muscle spasm,i was having muscle spasm and neck pain which ...,amrix | muscle spasm | i was having muscle spa...,4
22161,jardiance,"diabetes, type 2","brought my blood sugar and a1c down nicely, 6....","jardiance | diabetes, type 2 | brought my bloo...",4

In [24]:
val_df = pd.read_csv(Val_path, dtype={"text":str, "label":str})
display(val_df)

,drugName,condition,review,text,label
0,amoxicillin clavulanate,skin or soft tissue infection,this med was given as a result of a deep gouge...,amoxicillin clavulanate | skin or soft tissue ...,0
1,gianvi,premenstrual dysphoric disorde,i was given this generic by my pharmacy who di...,gianvi | premenstrual dysphoric disorde | i wa...,0
2,liletta,birth control,i have had the liletta iud in place for about ...,liletta | birth control | i have had the lilet...,0
3,ethinyl estradiol levonorgestrel,birth control,this is my second month on lutera and it has s...,ethinyl estradiol levonorgestrel | birth contr...,2
4,ethinyl estradiol norgestimate,birth control,sprintec is great for me. i have taken it for ...,ethinyl estradiol norgestimate | birth control...,4
...,...,...,...,...,...
5536,mirena,abnormal uterine bleeding,well after i was told i needed mirena for heav...,mirena | abnormal uterine bleeding | well afte...,4
5537,drospirenone ethinyl estradiol,birth control,"ive been on it for 3 months, and its pretty go...",drospirenone ethinyl estradiol | birth control...,3
5538,liraglutide,"diabetes, type 2","so far so good,,,been on it for 11 days have l...","liraglutide | diabetes, type 2 | so far so goo...",4
5539,ethinyl estradiol norgestimate,birth control,the first couple of months were a bit odd: i e...,ethinyl estradiol norgestimate | birth control...,4
5540,fiorinal,migraine,"ive had chronic migraines since 1984, almost o...",fiorinal | migraine | ive had chronic migraine...,3

In [25]:
# Rename column
train_df.rename(columns={'labels': 'label'}, inplace=True)
val_df.rename(columns={'labels': 'label'}, inplace=True)

# Save back
train_df.to_csv(Train_path, index=False)
val_df.to_csv(Val_path, index=False)

# Data Preparation

In [26]:
def build_example(text, label=None):
  try:
    system = "You are a helpful classifier. Reply with exactly one label from: " + ", ".join(Labels) + "."
    user = f"Text: {text}\nLabel options: " + ", ".join(Labels) + "\nAnswer with one label only."
    return {
        "system": system,
        "user": user,
        "assistant": label or "",
    }
  except:
    print(text, "\n")
    raise

recs = []
def df_to_hf(df, is_train=True): # converts df into a Hugging Face dataset
    recs = []
    try:
      for _, row in df.iterrows():
          recs.append(build_example(row["text"], Labels[row["label"]] if is_train else None))
      return Dataset.from_list(recs)
    except:
      print(row, "\n")
      # return Dataset.from_list(recs)


train_df = pd.read_csv(Train_path)
val_df = pd.read_csv(Val_path)

train_ds = df_to_hf(train_df)
val_ds = df_to_hf(val_df)

In [27]:
train_ds

Dataset({
    features: ['system', 'user', 'assistant'],
    num_rows: 22162
})

In [28]:
print(train_ds[:2]["assistant"])

['9-10 stars', '7-8 stars']

In [29]:
print(f"[Step 2] Train rows={len(train_df):,}, Val rows={len(val_df):,}")
print(f"[Step 2] Label examples: {train_df['label'].value_counts().to_dict()}")

[Step 2] Train rows=22,162, Val rows=5,541
[Step 2] Label examples: {4: 10618, 3: 4057, 0: 3760, 2: 2093, 1: 1634}

# Tokenizer + Quantization

In [30]:
tokenizer = AutoTokenizer.from_pretrained(Model)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/587k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

# LoRA Configuration

In [31]:
peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "down_proj", "up_proj"],
)

train_cfg = SFTConfig(
    output_dir=OUTPUT_DIR,
    num_train_epochs=2,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    eval_strategy="steps",
    eval_steps=500,
    logging_steps=50,
    save_steps=1000,
    bf16=True,
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    packing=False,
    dataset_num_proc=4,
    report_to="none",
    logging_dir="./logs",
)

# Training

In [32]:
def formatting_func(example):
    messages = [
        {"role": "system", "content": example["system"]},
        {"role": "user", "content": example["user"]},
        {"role": "assistant", "content": example["assistant"]},
    ]
    # Convert chat messages to a single text sequence (no tokenization yet)
    return tokenizer.apply_chat_template(messages, tokenize=False)

trainer = SFTTrainer(
    model=Model,                 # or model name string
    peft_config=peft_config,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    args=train_cfg,
    formatting_func=formatting_func,  # single-example formatter
)

config.json:   0%|          | 0.00/601 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.55G [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Applying formatting function to train dataset (num_proc=4):   0%|          | 0/22162 [00:00<?, ? examples/s]

Adding EOS to train dataset (num_proc=4):   0%|          | 0/22162 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=4):   0%|          | 0/22162 [00:00<?, ? examples/s]

Truncating train dataset (num_proc=4):   0%|          | 0/22162 [00:00<?, ? examples/s]

Applying formatting function to eval dataset (num_proc=4):   0%|          | 0/5541 [00:00<?, ? examples/s]

Adding EOS to eval dataset (num_proc=4):   0%|          | 0/5541 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=4):   0%|          | 0/5541 [00:00<?, ? examples/s]

Truncating eval dataset (num_proc=4):   0%|          | 0/5541 [00:00<?, ? examples/s]

In [33]:
trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

('/content/drive/MyDrive/Colab Notebooks/DataSci_266_NLP/Final_Project/Drug_Review/mistral_cls_adapter_001/tokenizer_config.json',
 '/content/drive/MyDrive/Colab Notebooks/DataSci_266_NLP/Final_Project/Drug_Review/mistral_cls_adapter_001/special_tokens_map.json',
 '/content/drive/MyDrive/Colab Notebooks/DataSci_266_NLP/Final_Project/Drug_Review/mistral_cls_adapter_001/chat_template.jinja',
 '/content/drive/MyDrive/Colab Notebooks/DataSci_266_NLP/Final_Project/Drug_Review/mistral_cls_adapter_001/tokenizer.model',
 '/content/drive/MyDrive/Colab Notebooks/DataSci_266_NLP/Final_Project/Drug_Review/mistral_cls_adapter_001/added_tokens.json',
 '/content/drive/MyDrive/Colab Notebooks/DataSci_266_NLP/Final_Project/Drug_Review/mistral_cls_adapter_001/tokenizer.json')